[parity]
chain = "smartNet.json"
db_path = "./data/miner"
[network]
port = 30303
[rpc]
port = 7434
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E"
reseal_on_txs = "none"
usd_per_tx = "0"
[misc]
logging = "lsync=trace,txqueue=trace"
