[parity]
chain = "smartNet.json"
db_path = "./data/miner"
[network]
port = 30303
reserved_peers = "./network.txt"
[rpc]
port = 7434
cors = "*"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
unlock = ["0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E", "0xa5F108b6d82b9F080325F935F3BAf89e0042CAC8", "0x001622be336710CA632dE00955928eb88832e51A"]
password = ["node.pwds"]
[mining]
engine_signer = "0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E"
reseal_on_txs = "none"
min_gas_price = 100
[misc]
logging = "lsync=trace,txqueue=trace"
[ipc]
disable = false
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
