[parity]
chain = "smartNet.json"
db_path = "./data/miner"
[network]
port = 30303
reserved_peers = "./network.txt"
[rpc]
port = 7434
cors = "*"
apis = ["all"]
[account]
unlock = ["0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E", "0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f", "0xa5F108b6d82b9F080325F935F3BAf89e0042CAC8", "0x001622be336710CA632dE00955928eb88832e51A"]
password = ["node.pwds"]
[mining]
engine_signer = "0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E"
reseal_on_txs = "none"
min_gas_price = 100
#tx_gas_limit = "249204912"
[misc]
logging = "lsync=trace,txqueue=trace,own_tx=trace"
[ipc]
disable = false
apis = ["all"]
[websockets]
disable = false
port = 8434
interface = "local"
origins = ["all"]
apis = ["all"]
hosts = ["all"]
[footprint]
tracing = "auto"
