[parity]
chain = "smartNet.json"
base_path = "relaynode"
[network]
port = 30304
reserved_peers = "./network.txt"
[rpc]
port = 7435
cors = "*"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[account]
password = ["node.pwds"]
[misc]
logging = "lsync=trace,txqueue=trace"
[ui]
port = 8181
[ipc]
disable = false
[websockets]
disable = false
port = 8435
interface = "local"
origins = ["all"]
apis = ["all"]
hosts = ["all"]
