[parity]
chain = "ropsten"
base_path = "/parity"
db_path = "/parity/chains"
keys_path = "/parity/keys"

[dapps]
path = "/parity/dapps"

[rpc]
disable = false
port = 8545
apis = ["all"]
cors = ["*"]
hosts = ["all"]
interface = "all"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["all"]
hosts = ["all"]
