[Eth]
NetworkId = 4
SyncMode = "fast"
LightPeers = 100
DatabaseCache = 768
GasPrice = 18000000000
EnablePreimageRecording = false

[Node]
DataDir = "/data/ethereum"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPVirtualHosts = ["ethereum"]
HTTPModules = ["net", "web3", "eth", "shh"]
WSHost = "127.0.0.1"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Dashboard]
Host = "ethereum"
Port = 8080
Refresh = 5000000000